patch: move to snap and add prometheus exporter + snap version checkl

diff --git a/rockcraft.yaml b/rockcraft.yaml
--- a/rockcraft.yaml
+++ b/rockcraft.yaml
@@ -3,7 +3,6 @@
 ---
 name: valkey
 base: ubuntu@26.04
-build-base: devel
 version: "9.1.0"
 summary: Valkey ROCK OCI
 description: |
@@ -19,36 +18,45 @@ platforms:
 
 run-user: _daemon_
 
+package-repositories:
+  - type: apt
+    components: [main]
+    suites: [resolute]
+    key-id: 6676E3F1A76ADBE4488944BF7D1A96D4BF78C79E
+    url: https://ppa.launchpadcontent.net/data-platform/prometheus-redis-exporter/ubuntu
+
 services:
   valkey:
     override: replace
     startup: enabled
     summary: Start Valkey
     command: "valkey-server --dir /var/lib/valkey"
+  metric_exporter:
+    override: replace
+    startup: enabled
+    summary: Start Metrics Exporter
+    command: "/bin/prometheus-redis-exporter"
 
 parts:
   valkey:
-    plugin: dump
-    source: bld:valkey
-    source-channel: 9.1-26.04/edge
+    plugin: nil
+    stage-snaps:
+      - valkey/9.1-26.04/edge
     stage-packages:
-      - bash
-      - libssl-dev
       - openssl
+      - prometheus-redis-exporter
+    override-stage: |
+      craftctl default
+      actual=$(${CRAFT_STAGE}/usr/bin/valkey-server --version | grep -oP '(?<=v=)[0-9.]+')
+      if [ "$actual" != "$CRAFT_PROJECT_VERSION" ]; then
+        echo "ERROR: binary version ($actual) does not match declared version ($CRAFT_PROJECT_VERSION)"
+        exit 1
+      fi
+      echo "Version check passed: $actual"
   valkey-user:
     plugin: nil
     after:
       - valkey
     override-build: |
-      # Needed for bare base
-      # https://github.com/canonical/rockcraft/issues/193#issuecomment-1429594574
-      mkdir $CRAFT_PART_INSTALL/etc
-      chmod 755 $CRAFT_PART_INSTALL/etc
-
-      # Create a user in the ${CRAFT_PART_INSTALL} chroot
-      groupadd -R ${CRAFT_PART_INSTALL} -g  584788 valkey
-      useradd -R ${CRAFT_PART_INSTALL} -M -r -g valkey -u 584788 valkey
-
-      # add directory for storing data
       mkdir -p ${CRAFT_PART_INSTALL}/var/lib/valkey
       chown -R 584788:584788 ${CRAFT_PART_INSTALL}/var/lib/valkey
